name: Windows Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    env:
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache vcpkg archives
        uses: actions/cache@v4
        with:
          path: ~\AppData\Local\vcpkg\archives
          key: vcpkg-openssl-${{ runner.os }}

      - name: Install OpenSSL
        run: vcpkg install openssl:x64-windows

      - name: Configure CMake
        run: >
          cmake -B build 
          -DCMAKE_BUILD_TYPE=Release 
          -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT\scripts\buildsystems\vcpkg.cmake"

      - name: Build Project
        run: cmake --build build --config Release